import { CtpApiRoot } from '@/utils/CommerceTools/CtpApiRoot';
import { Box, Button } from '@chakra-ui/react';
import { Product } from '@commercetools/platform-sdk';
import Head from 'next/head';
import React from 'react';

const getProductById = ({ productId }: { productId: string }) => {
  return CtpApiRoot.products().withId({ ID: productId }).get().execute();
};

type Props = {
  data: Product;
};

const ProductDetailPage = ({ data }: Props) => {
  const logServerSideProduct = () => {
    console.log(data);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box maxWidth={'1320px'} mx={'auto'}>
        <Button onClick={logServerSideProduct}>Log server product</Button>
      </Box>
    </>
  );
};

export async function getServerSideProps(context: any) {
  const { productId } = context.params;

  const products = await getProductById({ productId });

  return { props: { data: products.body } };
}

export default ProductDetailPage;
