import { CtpApiRoot } from '../utils/CommerceTools/CtpApiRoot';
import { Box, Button, Text } from '@chakra-ui/react';
import Head from 'next/head';
import { ProductPagedQueryResponse } from '@commercetools/platform-sdk';
import ProductList from '@/components/product/ProductList';

const getProducts = () => {
  return CtpApiRoot.products().get().execute();
};

type Props = {
  data: ProductPagedQueryResponse;
};

export default function Home({ data }: Props) {
  const logServerSideProducts = () => {
    console.log(data);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box maxWidth={'1320px'} mx={'auto'}>
        <Button onClick={logServerSideProducts}>Log server products</Button>

        <ProductList data={data} />
      </Box>
    </>
  );
}

export async function getServerSideProps() {
  const products = await getProducts();

  return { props: { data: products.body } };
}
