import { CtpApiRoot } from '@/utils/CommerceTools/ctpApiRoot';
import { Button, Text } from '@chakra-ui/react';
import Head from 'next/head';

const getProducts = () => {
  return CtpApiRoot.products().get().execute();
};

export default function Home() {
  const submitGetProd = async () => {
    try {
      const products = await getProducts();
      console.log(products);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Text>Hello World</Text>
      <Button onClick={submitGetProd}>get products</Button>
    </>
  );
}
